const CAN_DELETE_FOLDER = 'CAN_DELETE_FOLDER'
const CAN_UPLOAD_FILES = 'CAN_UPLOAD_FILES'
const CAN_DELETE_FILES = 'CAN_DELETE_FILES'
const CAN_CREATE_FOLDER = 'CAN_CREATE_FOLDER'

export default {
  CAN_DELETE_FOLDER,
  CAN_DELETE_FILES,
  CAN_UPLOAD_FILES,
  CAN_CREATE_FOLDER
}
