"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.findDocumentDetailsDrawer = exports.findDocumentActionsElement = exports.findSearchDatePicker = exports.findNattoDatePicker = exports.findNattoRadioGroup = exports.findSearchTreeItem = exports.findNattoTree = exports.findElTree = exports.findDeleteFileModalConfirmation = exports.findMultipleDocumentsCtas = exports.findMultipleDocumentsCta = exports.findDownloadCta = exports.findDeleteCta = exports.findMailToGedCard = exports.findPreviewCTAContainer = exports.findDownloadIcon = exports.findDeleteIcon = exports.findLoadingIcon = exports.findMpTableWrapper = exports.findMpButton = exports.findMpIcon = exports.findNattoCheckbox = void 0;
const useStyleguideStubs_1 = require("./useStyleguideStubs");
const PreviewCTAContainer_vue_1 = require("@/modules/Search/components/Modals/PreviewModal/PreviewModalHeader/CTAs/PreviewCTAContainer.vue");
const LoadingIcon_vue_1 = require("@/Common/components/Icons/LoadingIcon.vue");
const DeleteCta_vue_1 = require("@/modules/Search/components/Buttons/MultipleDocumentsCtas/DeleteCta.vue");
const DownloadCta_vue_1 = require("@/modules/Search/components/Buttons/MultipleDocumentsCtas/DownloadCta.vue");
const MultipleDocumentsCta_vue_1 = require("@/modules/Search/components/Buttons/MultipleDocumentsCtas/MultipleDocumentsCta.vue");
const DeleteIcon_vue_1 = require("@/Common/components/Icons/DeleteIcon.vue");
const DownloadIcon_vue_1 = require("@/Common/components/Icons/DownloadIcon.vue");
const MultipleDocumentsCtas_vue_1 = require("@/modules/Search/components/Buttons/MultipleDocumentsCtas/MultipleDocumentsCtas.vue");
const MailToGedCard_vue_1 = require("@/modules/DataManipulation/MailToGed/components/MailToGedCard.vue");
const DeleteFileModalConfirmation_vue_1 = require("@/modules/DataManipulation/Delete/DeleteFile/components/Modals/DeleteFileModalConfirmation.vue");
const NattoCheckbox_vue_1 = require("@/Common/components/Checkboxes/NattoCheckbox.vue");
const useElementStubs_1 = require("./useElementStubs");
const NattoTree_vue_1 = require("@/Common/components/Tree/NattoTree.vue");
const SearchTreeItem_vue_1 = require("@/modules/Search/components/Trees/SearchTreeItem.vue");
const NattoRadioGroup_vue_1 = require("@/Common/components/Radio/NattoRadioGroup.vue");
const NattoDatePicker_vue_1 = require("@/Common/components/Dates/NattoDatePicker.vue");
const SearchDatePicker_vue_1 = require("@/modules/Search/components/Filters/AdvancedSearchOptions/SearchDatePicker.vue");
const DocumentActionsElement_vue_1 = require("@/modules/Search/components/DocumentsTable/DocumentsTableElements/DocumentActionsElement.vue");
const { MpIcon, MpButton, MpTable } = (0, useStyleguideStubs_1.default)();
const { ElTree } = (0, useElementStubs_1.default)();
const findNattoCheckbox = (wrapper) => wrapper.findComponent(NattoCheckbox_vue_1.default);
exports.findNattoCheckbox = findNattoCheckbox;
const findMpIcon = (wrapper) => wrapper.findComponent(MpIcon);
exports.findMpIcon = findMpIcon;
const findMpButton = (wrapper) => wrapper.findComponent(MpButton);
exports.findMpButton = findMpButton;
const findMpTableWrapper = (wrapper) => wrapper.findComponent(MpTable);
exports.findMpTableWrapper = findMpTableWrapper;
const findLoadingIcon = (wrapper) => wrapper.findComponent(LoadingIcon_vue_1.default);
exports.findLoadingIcon = findLoadingIcon;
const findDeleteIcon = (wrapper) => wrapper.findComponent(DeleteIcon_vue_1.default);
exports.findDeleteIcon = findDeleteIcon;
const findDownloadIcon = (wrapper) => wrapper.findComponent(DownloadIcon_vue_1.default);
exports.findDownloadIcon = findDownloadIcon;
const findPreviewCTAContainer = (wrapper) => wrapper.findComponent(PreviewCTAContainer_vue_1.default);
exports.findPreviewCTAContainer = findPreviewCTAContainer;
const findMailToGedCard = (wrapper) => wrapper.findComponent(MailToGedCard_vue_1.default);
exports.findMailToGedCard = findMailToGedCard;
const findDeleteCta = (wrapper) => wrapper.findComponent(DeleteCta_vue_1.default);
exports.findDeleteCta = findDeleteCta;
const findDownloadCta = (wrapper) => wrapper.findComponent(DownloadCta_vue_1.default);
exports.findDownloadCta = findDownloadCta;
const findMultipleDocumentsCta = (wrapper) => wrapper.findComponent(MultipleDocumentsCta_vue_1.default);
exports.findMultipleDocumentsCta = findMultipleDocumentsCta;
const findMultipleDocumentsCtas = (wrapper) => wrapper.findComponent(MultipleDocumentsCtas_vue_1.default);
exports.findMultipleDocumentsCtas = findMultipleDocumentsCtas;
const findDeleteFileModalConfirmation = (wrapper) => wrapper.findComponent(DeleteFileModalConfirmation_vue_1.default);
exports.findDeleteFileModalConfirmation = findDeleteFileModalConfirmation;
const findElTree = (wrapper) => wrapper.findComponent(ElTree);
exports.findElTree = findElTree;
const findNattoTree = (wrapper) => wrapper.findComponent(NattoTree_vue_1.default);
exports.findNattoTree = findNattoTree;
const findSearchTreeItem = (wrapper) => wrapper.findComponent(SearchTreeItem_vue_1.default);
exports.findSearchTreeItem = findSearchTreeItem;
const findNattoRadioGroup = (wrapper) => wrapper.findComponent(NattoRadioGroup_vue_1.default);
exports.findNattoRadioGroup = findNattoRadioGroup;
const findNattoDatePicker = (wrapper) => wrapper.findComponent(NattoDatePicker_vue_1.default);
exports.findNattoDatePicker = findNattoDatePicker;
const findSearchDatePicker = (wrapper) => wrapper.findComponent(SearchDatePicker_vue_1.default);
exports.findSearchDatePicker = findSearchDatePicker;
const findDocumentActionsElement = (wrapper) => wrapper.findComponent(DocumentActionsElement_vue_1.default);
exports.findDocumentActionsElement = findDocumentActionsElement;
const findDocumentDetailsDrawer = (wrapper) => wrapper.findComponent({ name: 'document-details-drawer' });
exports.findDocumentDetailsDrawer = findDocumentDetailsDrawer;
//# sourceMappingURL=finders.js.map